<?php
namespace Proto\Test;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * * 规 范
 * namespace最后一个单词需与service名一致
 * service命名需大写开头 + 驼峰命名法
 * 每个thrift中只允许有一个service
 * 可以有多个function、struct
 * 
 * 生成对应语言命令:
 * thrift -r -out ../ --gen go test.thrift
 * thrift -r -out ../ --gen php:server test.thrift
 * 
 */
interface TestIf
{
    /**
     * @param string $msg
     * @return string
     */
    public function sendMessage($msg);
}
